# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CFBInfoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('href', models.URLField(max_length=512)),
                ('publication_date', models.DateField()),
                ('code', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CFBMenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64)),
                ('layer', models.IntegerField()),
                ('url_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='info_m2m_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.IntegerField()),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.CFBInfoDetail')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.CFBMenuInfo')),
            ],
        ),
    ]
