# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyNote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusinfo',
            name='layer',
            field=models.IntegerField(null=True),
        ),
    ]
