# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyNote', '0003_auto_20171205_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusinfo',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
