# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CFBInfoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('href', models.URLField(max_length=512)),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CFBMenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64)),
                ('layer', models.IntegerField()),
                ('url_length', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cfbinfodetail',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.CFBMenuInfo'),
        ),
    ]
