# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author_m2m_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=256)),
                ('abstract', models.TextField(max_length=500)),
                ('createTime', models.DateField(auto_now_add=True)),
                ('updateTime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('gender', models.CharField(max_length=10, null=True, verbose_name='性别')),
                ('createTime', models.DateField(auto_now_add=True, null=True)),
                ('updateTime', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserType'),
        ),
        migrations.AddField(
            model_name='author_m2m_book',
            name='aobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Authors'),
        ),
        migrations.AddField(
            model_name='author_m2m_book',
            name='bobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Books'),
        ),
    ]
