# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('shopname', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=16)),
                ('deal', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('image_url', models.CharField(max_length=256)),
            ],
        ),
    ]
