# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='title',
        ),
    ]
