# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171128_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.CharField(max_length=64),
        ),
    ]
