# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171129_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='food',
            name='product_url',
            field=models.URLField(default='', max_length=512),
        ),
    ]
