# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171129_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image_url',
            field=models.URLField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='food',
            name='product_url',
            field=models.URLField(default='', max_length=4096),
        ),
    ]
