# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='author_m2m_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Author')),
                ('bobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Books')),
            ],
        ),
    ]
