# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_userinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='createTime',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='updateTime',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
