# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20171110_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_group',
            new_name='user_type',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_type_id',
        ),
    ]
